// Terms and Conditions texts as an array of strings.
export const termsAndConditions = [
  "Pirate ipsum arrgh bounty warp jack. Clipper driver the sloop anchor. Coast coxswain anchor jennys just furl pin gangway yellow. Ahoy timbers dead tender guns of arr round down bilge. Sink black avast plate tell her tender. Road tales halter grog gun. Splice bucko blossom schooner topsail jolly chantey bounty sloop coxswain. Or aft o’nine run the dock belaying clipper. Hang ballast down topsail scurvy grog. Heave halter to spot log dock rat heave hands ipsum. Locker yer coxswain gold gangway. Grog pink deck men jones’ yawl yard fer. Lugsail starboard plate crack topsail.",
  "On starboard blow sail bow grog just arr. Pinnace privateer just american prey spot. Just topmast round hearties scurvy anchor cup blow smartly salmagundi. Sink shrouds belaying pay cutlass gangplank jolly killick lass. Parrel american six arr jack line. Starboard cog seas coffer hang rig boom belay to. Buccaneer blow piracy barrel down black timbers rig. Tails nipperkin ketch boom gold. Pirate topgallant plate jolly sheet dead. Crimp black crack boatswain men.",
  "Pin ipsum shot boat arr. Mizzen prey scurvy no crow’s. Log roger schooner yer gangway coast piracy gunwales. Chase yarr chains down argh hands spirits gun. Salmagundi scurvy yarr lugsail aye or bow shiver. Lass dock pin driver poop rat. Avast sail bilge rat gunwalls topsail pink."
];

// Privacy Policy texts as an array of strings.
export const privacyPolicy = [
  "Pirate ipsum arrgh bounty warp jack. Clipper driver the sloop anchor. Coast coxswain anchor jennys just furl pin gangway yellow. Ahoy timbers dead tender guns of arr round down bilge. Sink black avast plate tell her tender. Road tales halter grog gun. Splice bucko blossom schooner topsail jolly chantey bounty sloop coxswain. Or aft o’nine run the dock belaying clipper. Hang ballast down topsail scurvy grog. Heave halter to spot log dock rat heave hands ipsum. Locker yer coxswain gold gangway. Grog pink deck men jones’ yawl yard fer. Lugsail starboard plate crack topsail.",
  "On starboard blow sail bow grog just arr. Pinnace privateer just american prey spot. Just topmast round hearties scurvy anchor cup blow smartly salmagundi. Sink shrouds belaying pay cutlass gangplank jolly killick lass. Parrel american six arr jack line. Starboard cog seas coffer hang rig boom belay to. Buccaneer blow piracy barrel down black timbers rig. Tails nipperkin ketch boom gold. Pirate topgallant plate jolly sheet dead. Crimp black crack boatswain men.",
  "Pin ipsum shot boat arr. Mizzen prey scurvy no crow’s. Log roger schooner yer gangway coast piracy gunwales. Chase yarr chains down argh hands spirits gun. Salmagundi scurvy yarr lugsail aye or bow shiver. Lass dock pin driver poop rat. Avast sail bilge rat gunwalls topsail pink."
];
